### ISSUE TITLE
Would it be possible to add the config option to connect to an internal BB instance?

### ISSUE THREAD

**Issue by christianspecht** [christianspecht/scm-backup#25]
Paul Brown | 913.526.0939

On Oct 11, 2018, at 3:37 PM, Christian Specht <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]
________________________________

No, this shouldn't happen with the default settings.

I didn't notice it because I only tested the mails with a GitHub account (where I'm using GitHub's Octokit library, which doesn't log), but not with a Bitbucket account (where I'm calling the API in my own code, with full logging).

I just pushed another change - please try this version:
https://ci.appveyor.com/project/ChristianSpecht/scm-backup/builds/19444335/artifacts<https://urldefense.proofpoint.com/v2/url?u=https-3A__ci.appveyor.com_project_ChristianSpecht_scm-2Dbackup_builds_19444335_artifacts&d=DwMFaQ&c=UjmJbqZPMTat0o02F6csow&r=WSBk6TzDw3ltxBWUMipVBpFGVfczvxb4hoT-HqEPP-4&m=Fvd7xyTsLmRboRg5--LKirN2QSld6A7STKP34_mVuCE&s=DOxrM1kYIm25Pu0YeW7YgKGtk4dXv3KIg7JOew9JLk0&e=>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_christianspecht_scm-2Dbackup_issues_23-23issuecomment-2D429109743&d=DwMFaQ&c=UjmJbqZPMTat0o02F6csow&r=WSBk6TzDw3ltxBWUMipVBpFGVfczvxb4hoT-HqEPP-4&m=Fvd7xyTsLmRboRg5--LKirN2QSld6A7STKP34_mVuCE&s=g0LgCiKwaKI-LV9VJgGCU92Np8I3KMQ5AZxUaRFfhhg&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AYR9TFFxIAp7p8mQ0MGNA7xW3WAnulorks5uj6wVgaJpZM4XShyx&d=DwMFaQ&c=UjmJbqZPMTat0o02F6csow&r=WSBk6TzDw3ltxBWUMipVBpFGVfczvxb4hoT-HqEPP-4&m=Fvd7xyTsLmRboRg5--LKirN2QSld6A7STKP34_mVuCE&s=F7IqKyS6_YMCrpvEy13xScugGLpLDoO_OSy98Ec-vkc&e=>.

_Originally posted by @plbrownoptivcom in https://github.com/christianspecht/scm-backup/issues/23#issuecomment-429116556_

**Comment by christianspecht** [comment]
Probably possible, Bitbucket Server has an API too:
https://developer.atlassian.com/server/bitbucket/how-tos/command-line-rest/

**Comment by plbrownoptivcom** [comment]
This would be an awesome enhancement.

Paul Brown | 913.526.0939

On Oct 14, 2018, at 3:06 PM, Christian Specht <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]
________________________________

Probably possible, Bitbucket Server has an API too:
https://developer.atlassian.com/server/bitbucket/how-tos/command-line-rest/<https://urldefense.proofpoint.com/v2/url?u=https-3A__developer.atlassian.com_server_bitbucket_how-2Dtos_command-2Dline-2Drest_&d=DwMCaQ&c=UjmJbqZPMTat0o02F6csow&r=WSBk6TzDw3ltxBWUMipVBpFGVfczvxb4hoT-HqEPP-4&m=7VExGyuzrl-Ii3VDL_NZ8pZn8fyI1TxtQLPPMYcNF8g&s=maRoEIVFrUlP3nQ8NvSHyZRIBDIubaCylamTf8O9E2o&e=>

**Comment by christianspecht** [comment]
Thinking about this again, I see one big problem I don't know how to solve:
If I would implement this, it will be difficult to test.

AFAIK, the only version of BB Server that's freely available is a 30 day test version:
https://www.atlassian.com/software/bitbucket/download

1. For testing on my machine, I would need to install this version, and it will stop working after 30 days

2. There are [integration tests](https://github.com/christianspecht/scm-backup/tree/master/src/ScmBackup.Tests.Integration/Hosters) for the other supported hosters running on AppVeyor.
Unless there's a version of Bitbucket Server which I can install and setup unattended on AppVeyor, running integration tests for Bitbucket Server on AppVeyor won't be possible.

--> I'm afraid it's very unlikely that I will implement support for Bitbucket Server.

Think again: do you **really** need this?
Unless the cloud version, Bitbucket Server runs on a machine in your organization that you control.
**So it should be possible for you (or at least your admins) to directly backup the folder from that machine which contains all the repositories.**
