### ISSUE TITLE
Suggestion: password as an argument

### ISSUE THREAD

**Issue by bluesman80** [christianspecht/scm-backup#26]
Currently in order to use the tool with Bitbucket, one needs to save the app password to the settings.yml file. For security concerns it'd be better to be able to pass it as an argument to the program. It will come in handy when running a Jenkins job.

I'm new to this .NET core thing, so please let me know if I'm missing anything here.

Thank you.

**Comment by bluesman80** [comment]
Hi @christianspecht 
Thanks for your reply.

On a second thought, I think you are right about that putting an app password into a settings file is not that bad.

However, it would still be a good idea to make this improvement in a sane way, as you expressed. Hence, it should not adversely affect the user friendliness of the tool and at the same time it should allow the user to keep the passwords in a safer way.

For the first part of your comment, the format you suggested seems OK to me. I cannot come up with a better format.

For the second part of your comment, I agree with you. There is a plugin in Jenkins for binding the pre-saved credentials to environment variables temporarily. By temporarily I mean that the credentials are only available as environment variables while the job runs. Moreover, they are masked in the logs. The plugin allows the user to define the name of the variables per job, therefore if we can put the variable names into the settings file and make the program read them from the environment it would be safer and convenient at the same time.

**Comment by christianspecht** [comment]
This is now implemented in version 1.4.0.

Note that I still don't really like the idea of passing the arguments via command line, IMO the format looks messy.

So I only implemented the alternative with the environment variables, here's the documentation:
https://docs.scm-backup.org/en/1.4/config/#authentication

**Comment by bluesman80** [comment]
Thank you. I just tested it on a Jenkins ver. 2.204.1 running on Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1058-aws x86_64) and it works.
