### ISSUE TITLE
Gitlab support?

### ISSUE THREAD

**Issue by leifcr** [christianspecht/scm-backup#31]
Do you have plans for gitlab support?

**Comment by christianspecht** [comment]
I actually started implementing it a few months ago (https://github.com/christianspecht/scm-backup/commit/9b3ac136611159c056aa8f31e767d3b3164901c5), but didn't get very far :smiley:

**Comment by leifcr** [comment]
Awesome. I'll have a look. Not a .net developer, so this might take some time.

**Comment by christianspecht** [comment]
Don't get me wrong, I will eventually do it, I'm interested in backing up from Gitlab myself.

But I'll definitely fix #29 first...

**Comment by zgjavi** [comment]
Any advance? I would also be very interested in being able to backup gitlab. Thank you!

**Comment by christianspecht** [comment]
[Working on it](https://github.com/christianspecht/scm-backup/tree/gitlab), but will still take some time

**Comment by christianspecht** [comment]
Done in [version 1.3](https://github.com/christianspecht/scm-backup/releases/tag/1.3)
