### ISSUE TITLE
Upgrade to .NET Core 3.1 when it's released

### ISSUE THREAD

**Issue by christianspecht** [christianspecht/scm-backup#37]
3.0 doesn't make sense anymore because 3.1 [will be LTS and it's supposed to be released in December](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1-preview-1/)

https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by christianspecht** [comment]
... and maybe [compile to one single .exe including .NET Core](https://stackoverflow.com/q/50703578/6884)?

If .NET Core is not compiled into the .exe, even updating from .NET Core x.y to x.y+1 would be a breaking change because users would have to install the new .NET Core version.

**Comment by nzbart** [comment]
Now that 3.1 has been released, this would be a handy improvement. I'm running under Linux with the Snap package, which currently deploys only version 3.1.

I note that in your docs you mention:
>You need at least version 2.1 of the .NET Core runtime.

However, it appears that under .NET Core, the exact version is required. I get this error message:

>It was not possible to find any compatible framework version
>The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.  - The following frameworks were found:
>      3.1.0 at [/snap/dotnet-sdk/57/shared/Microsoft.NETCore.App]
>
>You can resolve the problem by installing the specified framework and/or SDK.
>
>The specified framework can be found at:
>  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=debian-x64

**Comment by nzbart** [comment]
An update on the above comment: I've recompiled from source under .NET Core 3.1 running on Debian Linux, and it appears to be working well.
