### ISSUE TITLE
Is there a way to target local Bitbucket servers rather than the primary cloud servers?

### ISSUE THREAD

**Issue by the-virus-of-doom** [christianspecht/scm-backup#42]
I just found your project today and think it is great work! I am trying to create a local copy of my organization's projects from a local Bitbucket server before a migration to GitHub, but I am not sure how to change the location in the settings. Is a local Bitbucket repo server supported or should I look for another tool to make the copy?

Thank you for all of the time and effort you have put into this! I might start using it personally once some of my own projects start growing!

**Comment by christianspecht** [comment]
Sorry, local Bitbucket servers are not supported and probably never will. [Here's an explanation why](https://github.com/christianspecht/scm-backup/issues/25#issuecomment-434444008).

I just added a note about this to the docs.
