### ISSUE TITLE
Folder Issues

### ISSUE THREAD

**Issue by kuroiokami** [christianspecht/scm-backup#48]
Trying to run this on a Mac and i'm probably being a blind fool but can't get it to read my local folder attribute. Keeps giving me the error Local Folder is missing!

I've tried pretty much every possible way to target a folder as I could possibly think of along with changing names etc. Also once it errors out it seems to be looking for other files in c:\projects\scm-backup\src\ScmBackup\Http\MailKitEmailSender which isn't a folder that comes with the archive?

**Comment by christianspecht** [comment]
I'm developing on Windows only, so all path examples I'm using are for Windows - I don't have access to any Mac or Linux systems.

The only Mac-related thing that I know of is [this StackOverflow question which I answered last year](https://stackoverflow.com/a/57366138/6884) (first part of the answer) - the asker is a Mac user and apparently had similar problems with the path.  
That's all I know about Mac folder structure :sunglasses: 

If you get the path right with this information, could you give me a working example for Mac so that I can add it to the documentation? Thanks!

**Comment by christianspecht** [comment]
Wait a minute...the error message is "Local folder is missing"?

That message is generated [here](https://github.com/christianspecht/scm-backup/blob/ae7edc38fa49c6770d928f7e1d4ca2d8e68736a7/src/ScmBackup/ValidatingConfigReader.cs#L37):

    if (String.IsNullOrWhiteSpace(config.LocalFolder))
    {
        this.logger.Log(ErrorLevel.Error, Resource.LocalFolderMissing);
        return null;
    }

This looks as if there's no `localFolder` defined in your settings file. Can you show the part of your settings file where you defined the folder?

**Comment by kuroiokami** [comment]
Hey Christian, sorry for the late reply and thank you for keeping up with me. I ended up figuring out the issue. It was actually an issue on the auth side. I forgot which exact field it was but either lack of authName (vs just name) or the org/user not being correct gave me that error. I guess it's referring to no local folder on the repo's end? Basically I looked at the directions on https://docs.scm-backup.org/en/latest/config/#sources and didn't fully look at the specialized pages clearly. We can go ahead and close this. I ended up making a docker image based off a forum post to deploy this for our environment!

**Comment by christianspecht** [comment]
Glad to hear it worked for you!  
I'm closing this issue now, but I'm always interested in example configurations that cause misleading error messages, so I can change them into meaningful messages :smile: 

So if you still have the version of the configuration file that caused the issue, I'd love to see it.  
(if you don't want to post it here, you can send it to me via email, see the "Imprint" link at the bottom of the docs).

And the Docker thing sounds interesting as well...so you made an image containing .NET Core and SCM Backup?

**Comment by eric-gagnon** [comment]
I had a similar error but I had deleted the ending single quote while changing the path.
localFolder: '/backup/something-something

A more a precise error could have helped the diagnostic but it was my error.
