### ISSUE TITLE
Mercurial was NOT found

### ISSUE THREAD

**Issue by EnricoRav** [christianspecht/scm-backup#56]
Hello, 
i read the guide and configured settings.yml as in this image:

![image](https://user-images.githubusercontent.com/66881574/84575198-b66f9400-adab-11ea-97b8-cf14840ecb89.png)

I using TortoiseHg on my PC but for try to solve the problem i have installed also Mercurial from Setup but nothing change.

Hg is in the search path, if i open cmd and i digit "hg" it work.

The error are alwais the same as you can see in the log below:

![image](https://user-images.githubusercontent.com/66881574/84575301-6c3ae280-adac-11ea-8800-e8d2590522ad.png)

Note: if i change settings.yml commenting out the scms section the error are always the same, but if i put a wrong path into the settings.yml as in the image below:

![image](https://user-images.githubusercontent.com/66881574/84575438-3e09d280-adad-11ea-9320-03bc9b200d6f.png)

the errors becomes:

![image](https://user-images.githubusercontent.com/66881574/84575450-52e66600-adad-11ea-843f-2caf1d002824.png)

I wait for your help, thanks in advance.
Enrico

**Comment by christianspecht** [comment]
Can you open cmd on your machine, enter `hg version` and show me the result?

That‘s what SCM Backup actually does when it tries to find Mercurial:
It runs `hg version` and [checks if the output contains the string „mercurial distributed scm“](https://github.com/christianspecht/scm-backup/blob/master/src/ScmBackup/Scm/MercurialScm.cs#L40).

When I implemented this, this logic worked for all Mercurial versions I tested it with. But maybe the text was changed in one of the newer Mercurial versions.

PS:
You know that Bitbucket will drop Mercurial support and delete all Mercurial repositories in about two weeks?

**Comment by EnricoRav** [comment]
Hello,
here the 2 version of the Hg installed in my PC.
The first is the new one installed to try to solve the problem.
The second is the one installed with TortoiseHg (an old version).

![image](https://user-images.githubusercontent.com/66881574/84708404-bc5aa600-af60-11ea-8380-be2f53dc5387.png)

**Comment by EnricoRav** [comment]
I know who BitBucket will drop Mercurial support and delete the repo in the next 2 weeks, it is for that who i need a complete backup of all my repos. 
I have more of 50 repo's in 3 different workspace.

**Comment by christianspecht** [comment]
> The bug is the string who don't match the "Italian" translation, perhaps it's better separately test the existence of the strings "mercurial" and "scm".
>
> I solved the bug deleting the folder Locale\it under Hg installation folder, without Mercurial localization file the returned string is the english version and SCM Backup works!

OK, this is interesting. I wasn't aware that Mercurial is localized (and I'm in Germany and my machine has German settings :sunglasses: ).  
Now I see that my current Mercurial installation (v5.0.2) is partly localized. The output of `hg version` is in English, but other commands output a mixture of English and German. So it seems they are in the process of localizing it.

I need to check if there's a language-agnostic way to get the information SCM Backup needs (it's not only "does hg exist on this machine" - it's also the version number that SCM Backup shows)

**Comment by christianspecht** [comment]
> I tryied to use hggit to convert the repos into Git and continue to use BitBucket but i haven't found any version of "Mercurial + Python + Dulwich + Hggit" not buggy.
> I can't successfully converted no one repo ... :-(
> Can you suggest me a method to do a good conversion of the Mercurial repos to Git?

I converted about 40 HG repos to Git in the last few month (work and private).

I didn't use anything special, [just the HgGit version that's bundled with TortoiseHG](https://stackoverflow.com/a/59863847/6884).  
I'm 95% sure that the following is all you need (if not, ask again and I'll take a closer look):

1. Open `%userprofile%\mercurial.ini` and add this:

    ```
    [extensions]
    hggit =

    [git]
    branch_bookmark_suffix=_bm
    ```

    The first one activates the hggit plugin (which comes with TortoiseHG, it just needs to be activated), and the second one is needed if your HG repo has named branches ([you need to convert each branch that you want to keep into a bookmark, because hggit supports only bookmarks](https://foss.heptapod.net/mercurial/hg-git#gitbranch_bookmark_suffix). Note: [there are ways to automate this](https://stackoverflow.com/questions/57716968/convert-bitbucket-mercurial-repository-to-git-maintain-branches-and-history-on/59863847#comment109045784_59863847))

2.  Save this as a batch file and execute it for each repo that you want to convert:

    ```
    set basedir=C:\Code\
    set hgrepo=MyRepository
    set gitrepo=%hgrepo%-Git

    c:
    rd /s /q %basedir%%gitrepo%

    md %basedir%%gitrepo%
    cd %basedir%%gitrepo%
    git init

    cd %basedir%%hgrepo%
    hg bookmarks hg
    hg push ../%gitrepo%

    cd %basedir%%gitrepo%
    git checkout -b master hg

    pause
    ```

    This will convert the local Mercurial repo `C:\Code\MyRepository` to a new local Git repo in `C:\Code\MyRepository-Git`.

**Comment by christianspecht** [comment]
I never tried 4.5.2, I can just tell you that I did all my repo conversions with 5.0.2, which worked without bugs.

Maybe you should try a fresh installation (or another machine). In one of your first posts, you wrote that you have multiple HG versions installed. I have no idea where HG stores its extensions, but when you tried to convert the repo, maybe the HG installation that was actually used somehow found the wrong hggit version?

**Comment by christianspecht** [comment]
This issue is now auto-closed because I just merged the commit into master where I fixed the actual problem (Mercurial was not found).

Feel free to continue asking about converting HG repos to Git!

**Comment by EnricoRav** [comment]
Hello Christian,
i removed all versions of TortoiseHg, SourceSafe, Mercurial and Git from my PC. 
Then i done a fresh installation of TortoiseHg 5.0.2 and Git 2.27.0, and with this configuration the hggit extension works fine.
Only some trouble to understand how to convert all the active branchs. I discovered that i must set a bookmark for every active branch on the hg repo before doing the push to the new git repo. 
Another trick is that the bookmarks name can't contains any spacing characters or any characters don't allowed into the git's branchs name. If a don't allowed character is presents into the branch name the hggit crash and the conversion fail. 
With this tricks i modified your example (.bat) and i converted successfully a complex repo with 5 active branchs. In your example the "default" branch is converted as "hg" in git, after conversion i added a deletion of "hg" branch into git repo to clean the conversion of branch "default" to "master". 
Thank you very much for your help!!
