### ISSUE TITLE
How to disable the backup for Mecurial Repos?

### ISSUE THREAD

**Issue by IT-Yogi** [christianspecht/scm-backup#60]
Hi, 

maybe a dumb question, but how can I disable the backups for mercurial repos? I've found nothing at your documentation and if I remove the path to hg.exe the backup process will completly abort. 
Without disabling the legacy repos, the backup process will fail with first mecurial repo. 
Any ideas? 

![image](https://user-images.githubusercontent.com/62701790/90877151-e9ce3080-e3a3-11ea-8985-588122dfa26e.png)

**Comment by christianspecht** [comment]
This is a bug on Bitbucket's side - even though they deleted/disabled/*[whatever]* all Mercurial repos almost 2 months ago, their API still returns them (and of course backing them up fails).

I have the same problem with the user I'm using for integration tests:  
https://bitbucket.org/scm-backup-testuser/
The Mercurial repo `scm-backup-test` is even still visible in the UI, but I can't open it in the UI, and cloning fails.

I'll publish a bugfix, so SCM Backup ignores all HG repos that the Bitbucket API returns.

**Comment by IT-Yogi** [comment]
Hey Christian, 

Thanks for the clarification and the lightspeed support. 
I really appreciate it!
