### ISSUE TITLE
Suggestion: Add includeRepos property to allow more fine-grained control of what repos are backed up

### ISSUE THREAD

**Issue by jaltin** [christianspecht/scm-backup#64]
Hi,

First of all, thank you for a GREAT tool @christianspecht! It works really well and is easy to use.

I have a suggestion for an improvement. 

Some of the workspaces I want to back up has LOTS of repos. Repos are added frequently (meaning the list changes so I can't really use ignoreRepos property).

I am only interested in backing up a few repos, so it would be great if a new property 'includeRepos' could be added. That would allow me to only specify the ones I want to back up.

Thanks!

Jonas

**Comment by christianspecht** [comment]
Sure...that's no big deal and basically a copy of the ignoreRepos funtionality. I will add this for the next release.

**Comment by jaltin** [comment]
Great, thanks a lot!
